
export const LISTAR_VIAJES = 'LISTAR_VIAJES';
export const PUBLICAR_VIAJE = 'PUBLICAR_VIAJE';
export const REGISTRAR_PASAJERO = 'REGISTRAR_PASAJERO';
export const REGISTRAR_CONDUCTOR = 'REGISTRAR_CONDUCTOR';
export const LISTAR_USUARIO = 'LISTAR_USUARIO';
export const SOLICITAR_VIAJE = 'SOLICITAR_VIAJE';



